source 'https://rubygems.org'

gem 'rails', '3.2.22'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'test-unit'
gem 'mysql2'
gem 'activerecord-mysql2-adapter'
gem 'rails-api'
gem 'railties'
gem 'actionpack'
gem 'actionmailer'
gem 'activemodel'
gem 'couch_potato'
gem 'tzinfo'
gem 'faraday'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
